### PR TITLE
Search bar

### PR DESCRIPTION
**Pull request by Aux5**
### Purpose:

Allows users to search for products

### How it fits in context of the project:
(Link to ticket: # )

fulfills ticket #6 

### Specific Feature affected:

Layout.cs
productsController.cs

### How to test (Be thorough!):

1. Check into my branch bs-search
2. Run the build
3. On the home page there should be a search bar
4. Search for anything like "socks"
5. This should route you to the product index page and display the search results
6. Run Dotnet Test in the terminal
7. There should be 4 tests and 0 failures

### CODE REVIEW

**Comment by Rian501** [comment]
The ticket says "given that the user is authenticated" -- it let me do it even when I was not authenticated.

**Comment by Aux5** [comment]
Dang, I'll fix it

**Comment by Aux5** [comment]
So hiding the search bar until they're logged in is okay?

**Comment by Rian501** [comment]
Yes that would be okay

**Comment by Rian501** [comment]
Good job Brett ✨ 
Please open a separate ticket to not display the uid of the user who posted the product on the search result page. :+1:

**Comment by Aux5** [comment]
Will do, Thanks!

**Pull request merged**
